name: release CI, CD workflows.
on: 
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: show dir
        run: ls -la

      - name: setup - npm instal
        run: npm install

      - name: show node modules
        run: ls -la

      - name: CI
        run: npm ci
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        
